# Generated by Django 4.1.1 on 2022-09-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ('pin',)},
        ),
    ]
