# Generated by Django 4.1.1 on 2022-09-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0002_alter_notes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={},
        ),
    ]
