# Generated by Django 4.1.1 on 2022-09-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0004_notes_created_at_notes_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(max_length=40000),
        ),
    ]
