# Generated by Django 4.1.1 on 2022-09-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0005_alter_notes_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='updated_at',
        ),
    ]
