# Generated by Django 4.1.1 on 2022-09-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0011_notes_created_at_notes_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
