# Generated by Django 4.1.1 on 2022-09-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0012_alter_notes_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='notes',
            name='updated_at',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
