# Generated by Django 4.1.1 on 2022-09-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0016_alter_notes_created_at_alter_notes_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='tagline',
            field=models.CharField(default='#MyTagline', max_length=30),
        ),
    ]
