# Generated by Django 4.1.1 on 2022-09-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0017_notes_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(blank=True, max_length=40000, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
