# Generated by Django 4.1.1 on 2022-09-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep', '0018_alter_notes_created_at_alter_notes_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='tagline',
            field=models.CharField(default='', max_length=30),
        ),
    ]
